const LOAD_ACCOUNTS = 'LOAD ACCOUNTS'
const CREATE_ACCOUNT = 'CREATE ACCOUNT'
const UPDATE_ACCOUNT = 'UPDATE ACCOUNT'
const REMOVE_ACCOUNT = 'REMOVE ACCOUNT'

const LOAD_TRANSACTIONS = 'LOAD TRANSACTIONS'
const CREATE_TRANSACTION = 'CREATE TRANSACTION'

const LOAD_WATCHES = 'LOAD WATCHES'

const LOAD_NEWS = 'LOAD NEWS'

export {
  LOAD_ACCOUNTS,
  CREATE_ACCOUNT,
  UPDATE_ACCOUNT,
  REMOVE_ACCOUNT,
  LOAD_TRANSACTIONS,
  CREATE_TRANSACTION,
  LOAD_NEWS,
  LOAD_WATCHES
}
